liber/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from usuarios.views import UserCreate, logout_view
from livros.views import LivroIndex

from liber import settings

urlpatterns = [
    path('', LivroIndex.as_view(), name='livros_index'),
    path('admin/', admin.site.urls),
    path('livros/', include('livros.urls')),
    path('perfil/', include('usuarios.urls')),

    path('login/', auth_views.login, {'template_name':'perfil/login.html'}, name="login"),
    path('logout/', logout_view, name ="logout"),
    path('cadastrar/',UserCreate.as_view(), name="cadastrar"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livros/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

# Django local
from . import views
from usuarios.views import marcar_livro_lido
#, AvaliaLidoCreate


app_name = 'livros'
urlpatterns = [
    #path('', views.LivroIndex.as_view(), name='livros_index'),
    path('', views.ListLivros.as_view(), name='lista_livros'),
    path('<int:pk>/', views.LivroDetail.as_view(), name='livros_detail'),
    path('<int:pk>/detail', login_required(views.LivroDetailLogado.as_view()), name='livros_detail_logado'),
    path('new', views.LivroCreate.as_view(), name='livros_new'),
    path('autor/new', views.AutorCreate.as_view(), name='autor_new'),
    path('<int:pk>/edit', views.LivroUpdate.as_view(), name='livros_edit'),
    path('<int:pk>/delete', views.LivroDelete.as_view(), name='livros_delete'),
    path('<int:pk>/adiciona', views.adiciona_livro_na_estante, name='adiciona'),
    path('<int:pk>/lido', marcar_livro_lido, name='livrolido'),
    path('<int:pk>/medialivros', views.media_cada_livro, name='medialivros'),
    path('<int:pk>/avalia', views.AvaliaLidoCreate.as_view(), name='avalia_livro'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
# from views import RegistrarUsuarioView

# papra importar imagem
from django.conf import settings
from django.conf.urls.static import static

# Django local
from . import views
from livros.views import apagar_livro_da_estante, altera_status_livro

app_name = 'usuarios'
urlpatterns = [

    path('', login_required(views.UserIndex.as_view()), name='usuarios_index'),
    path('<int:pk>', views.UserDetail.as_view(), name='home'),
    path('<int:user>/estante', login_required(views.PerfilEstanteList.as_view()), name='estante'),
    path('<int:user>/estante/<int:livro>/apagar', apagar_livro_da_estante, name='apagar_livro' ),
    path('<int:user>/estante/<int:livro>/alterar', altera_status_livro, name='altera_status_livro' ),
    path('<int:user>/estante/<int:livro>', views.LivroEmprestimoDetail.as_view(), name='pedir_emprestado_detail'),
    path('<int:user>/estante/<int:livro>/emprestimo', views.fazer_pedido_de_emprestimo, name='pedir_emprestado'),
    path('<int:user>/avaliacaolivro',(views.LivrosAvaliados.as_view()), name='avaliacaolivro'),
    path('<int:user>/sugestao', views.SugestaoLivro.as_view(), name='sugestao' ),
    path('<int:user>/avaliacao',views.Avaliacao.as_view(), name='avaliacao'),
    path('<int:user>/emprestimos', views.livros_emprestados.as_view(), name='emprestados'),
    path('<int:user>/emprestimos/<int:emprestimo>', views.EmprestimoDetail.as_view(), name='emprestimo_detail'),
    path('<int:user>/emprestimos/<int:emprestimo>/aceita', views.aceitar_emprestimo, name='aceita_emprestimo'),
    path('<int:user>/emprestimos/<int:emprestimo>/cancela', views.cancelar_emprestimo, name='cancelar_emprestimo'),
    path('<int:user>/devolver/<int:emprestimo>/devolver', views.devolver_livro, name='devolver_livro'),
    path('<int:user>/emprestimos/<int:emprestimo>/avaliar', views.confirmar_devolucao, name='avaliar_emprestimo'),
    path('<int:user>/devolver', views.livros_devolver.as_view(), name='livros_devolver'),
    path('<int:user>/historico', views.historico.as_view(), name='historico'),
    #path('<int:user>/testeemprestimo', views.teste_historico_emprestimo.as_view(), name='testeemprestimo'),
    #path('<int:user>/testeemprestimo/<int:emprestimo>/aceita', views.aceitar_emprestimo, name='aceita_emprestimo'),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/models.py
from django.db import models

from livros.models import Livro, Categoria

from django.contrib.auth.models import User

SEXO_USUARIO = (
    ('F', 'Feminino'),
    ('M', 'Masculino'),
)

NOTA_LIDO = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10),
)

STATUS_EMPRESTIMO = (
    ('S', 'Solicitado'),
    ('EA', 'Em andamento'),
    ('OK', 'Concluído'),
    ('ED', 'Em Devolução'),
    ('C', 'Cancelado')
)


class Perfil(models.Model):

    usuario = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    telefone = models.CharField(max_length=15, null=True)
    data_de_nascimento = models.DateField(blank=True)
    sexo = models.CharField(max_length=1, choices=SEXO_USUARIO, blank=True , null=True)
    categorias_preferidas = models.ManyToManyField(Categoria)
    imagem_perfil = models.ImageField(upload_to='imagem_perfil/', default='imagem_perfil/user.png')
    livros = models.ManyToManyField(Livro, through='AvaliaLido' )


    def __str__(self):
        return self.usuario.username

    class Meta:
        verbose_name='Perfil'
        verbose_name_plural= "Perfis"


"""
    @property
    def email(self):
        return self.usuario.email
"""
STATUS_LIVRO = (
    ('D', 'Disponível'),
    ('E', 'Emprestado'),
)

class Estante(models.Model):

    nome = models.CharField(max_length=30, blank=False , default="Estante")
    perfil_dono = models.OneToOneField(Perfil,  on_delete=models.CASCADE, null=True)
    livros = models.ManyToManyField(Livro, through='EstanteLivro')

    def __str__(self):
        return '{}-> {}'.format(self.nome, self.perfil_dono)


class EstanteLivro(models.Model):
    estante = models.ForeignKey(Estante, on_delete=models.CASCADE)
    livro_adicionado = models.ForeignKey(Livro, on_delete=models.CASCADE)
    data_adicionado = models.DateField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_LIVRO, blank=False , null=False, default='D')

    def __str__(self):
        return '{}-> {}'.format(self.estante, self.livro_adicionado)

class AvaliaLido (models.Model):

    lido = models.BooleanField(default=False)
    perfil_avaliador= models.ForeignKey(Perfil, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE)
    nota = models.IntegerField(choices=NOTA_LIDO, null=False)
    comentario = models.TextField(null=True, blank=True)

    def __str__(self):
        return '{} {} {}'.format(self.livro, self.perfil_avaliador, self.nota)


class Emprestimo (models.Model):
    perfil_do_dono = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name="solicitado")
    perfil_solicitante = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name="solicitante")
    livro_emprestado = models.ForeignKey(EstanteLivro, on_delete=models.CASCADE)
    data_emprestimo= models.DateField(auto_now=True)
    data_devolucao= models.DateField(null=True)
    status_emprestimo = models.CharField(max_length=2, choices=STATUS_EMPRESTIMO, blank=False , null=False, default='S')
    mensagem_de_quem_pede = models.CharField(null=True, blank=True, max_length=200)
    mensagem_resposta = models.CharField(null=True, blank=True,max_length=200)

    def __str__(self):
        return'Dono >{}, para {},{}'.format(self.perfil_do_dono.usuario.username, self.perfil_solicitante, self.livro_emprestado)


class AvaliaEmprestimo (models.Model):
    nota = models.IntegerField(choices=NOTA_LIDO)
    Emprestimo_avaliado = models.OneToOneField(Emprestimo, on_delete=models.CASCADE)
    mensagem_de_avaliacao = models.CharField(null=True, blank=True,max_length=200)

    def __str__(self):
        return '{}'.format(self.Emprestimo_avaliado)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import Perfil, AvaliaLido, Emprestimo, AvaliaEmprestimo

SEXO_USUARIO = (
    ('F', 'Feminino'),
    ('M', 'Masculino'),
)

class CadastroForm(UserCreationForm):

    telefone = forms.CharField()
    data_de_nascimento = forms.DateField()
    sexo = forms.ChoiceField(widget=forms.Select, choices=SEXO_USUARIO) #SelectCharWidget(sexo=SEXO_USUARIO))
    #imagem_perfil = forms.ImageField()

    class Meta:
        model = User
        fields = ('username','password1','password2','telefone','data_de_nascimento','sexo')#,'imagem_perfil')

"""
class RegistrarUsuarioForm(forms.Form):

    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    data_de_nascimento = forms.DateField(required=True)
    sexo = forms.CharField(required=True)
    imagem_perfil = forms.ImageField(required=False)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor verifique os dados informados.')
            valid = False

        user_exists = User.objects.filter(username=self.data['email']).exists()

        if user_exists:
            self.adiciona_erro('Usuário ja existente')
            valid = False
        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)
"""

class AvaliaForm(ModelForm):
    class Meta:
        model = AvaliaLido
        fields = ['nota','comentario']

class PedirLivroEmprestadoForm(ModelForm):
    class Meta:
        model = Emprestimo
        fields = ['data_devolucao', 'mensagem_de_quem_pede']

class EmprestimoForm(ModelForm):
    class Meta:
        model = Emprestimo
        fields = ['mensagem_resposta']
        #mensagem_de_quem_pede = forms.CharField(required=False, widget=forms.Textarea(attrs={'class':'form-control','rows':1,'cols':10,'placeholder':'keword values'}))


class AvaliacaoEmprestimoForm(ModelForm):
    class Meta:
        model = AvaliaEmprestimo
        fields = ['nota','mensagem_de_avaliacao']

usuarios/templates/dashboard/avaliacao.html
<h2>Avalia livro</h2>

<form action="{% url 'livros:avalia_livro' pk=livro.id %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="OK">
</form>

usuarios/templates/dashboard/base_dashboard.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png"%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static "assets/img/favicon.png"%}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <link href="{% static "assets/css/bootstrap2.min.css"%}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static "assets/css/animate.min.css"%}" rel="stylesheet" />

    <!--  Paper Dashboard core CSS    -->
    <link href="{% static "assets/css/paper-dashboard.css"%}" rel="stylesheet" />
    <link href="{% static "assets/css/dashboard.css"%}" rel="stylesheet" />

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static "assets/css/themify-icons.css"%}" rel="stylesheet">

</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-background-color="white" data-active-color="danger">
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="{% url 'livros_index' %}" class="simple-text">
                        <img src="{% static "assets/img/logo-letras.png"%}" class="logotipo" />
                    </a>
                </div>

                <ul class="nav">
                    <li>
                        <img src="{{ perfil.imagem_perfil.url }}"></img>
                        <h2> {{ perfil.usuario }}</h2>
                    </li>
                    {% if request.user.perfil == perfil %}
                    {% block acompanhamento %}
                    <li class="active">{% endblock %}
                        <a href="{% url 'usuarios:home' perfil.id %}">
                            <i class="ti-panel"></i>
                            <p>Acompanhamento</p>
                        </a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="#">
                            <i class="ti-user"></i>
                            <p>Perfil de Usuário</p>
                        </a>
                    </li>
                    {% block avaliacao %}
                    <li> {% endblock %}
                        <a href="{% url 'usuarios:avaliacao' user=perfil.id %}">
                            <i class="ti-search"></i>
                            <p>Ver Avaliações</p>
                        </a>
                    </li>
                    {% block estante %}
                    <li> {% endblock %}
                        <a href="{% url 'usuarios:estante' perfil.id %}">
                            <i class="ti-book"></i>
                              {% if request.user.perfil == perfil %}
                                <p>Minha Estante</p>
                              {% else %}
                              <p>Estante</p>
                              {% endif %}
                        </a>
                    </li>
                      {% if request.user.perfil == perfil %}
                    <li>
                        <a href="#" data-toggle="modal" data-target="#myModal">
                            <i class="ti-bookmark"></i>
                            <p>Quero Sugestão</p>
                        </a>
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title text-center" id="exampleModalLabel">Olha o que achamos para você!</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        {% if sugestao %}
                                          <ul>
                                            {% for livross in sugestao %}
                                            <li><a href= "{% url 'livros:livros_detail' pk=livross.id %}" >{{ livross.titulo }}, de {{livross.autores.first}}</a></li>
                                                {%for cat in livross.categorias.all%}
                                                    {{cat}},
                                                {% endfor %}
                                            {% endfor %}
                                          </ul>
                                        {% else %}
                                          <p>Não tem livro registrado</p>
                                        {% endif %}

                                    </div>
                                    <div class="modal-footer">
                                        <div class="divider"></div>
                                        <div class="right-side">
                                            <button type="button" class="btn btn-danger btn-link">Mais sugestões</button>
                                        </  div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar bar1"></span>
                            <span class="icon-bar bar2"></span>
                            <span class="icon-bar bar3"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'usuarios:home' pk=request.user.perfil.id %}">Minha Conta</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a class="buy-button" href="{% url 'usuarios:usuarios_index' %}">
                                    <i class="fa fa-user-circle-o"></i>
                                    <br>
                                </a>
                            </li>
                            <li>
                            <a class="buy-button" href="{% url 'livros:lista_livros' %}">
                                <i class="fa fa-book"></i>
                                <br>
                            </a>
                            </li>
                            <li>
                                <a href="{% url 'usuarios:emprestados' user=request.user.perfil.id %}">
                                    <i class="ti-clipboard"></i>
                                    <p>Meus Empréstimos</p>
                                </a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <p class="notification">5</p>
                                    <p>Notificações</p>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Notificação 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Notificação 2</a>
                                    </li>
                                    <li>
                                        <a href="#">Notificação 3</a>
                                    </li>
                                    <li>
                                        <a href="#">Notificação 4</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="ti-settings"></i>
                                    <p>Configurações</p>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'logout' %}">
                                    <i class="fa fa-sign-out"></i>
                                    <p>Sair</p>
                                </a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>



{% block body %}

{% endblock %}


</body>

<!--   Core JS Files   -->
<script src="{% static "assets/js/jquery-1.10.2.js"%}" type="text/javascript"></script>
<script src="{% static "assets/js/bootstrap2.min.js"%}" type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="{% static "assets/js/bootstrap-checkbox-radio.js"%}"></script>

<!--  Charts Plugin -->
<script src="{% static "assets/js/chartist.min.js"%}"></script>

<!--  Notifications Plugin    -->
<script src="{% static "assets/js/bootstrap-notify.js"%}"></script>
<script src="{% static "assets/js/paper-dashboard.js"%}"></script>
<script src="{% static "assets/js/demo.js"%}"></script>

<script type="text/javascript">
    $(document).ready(function () {

        demo.initChartist();

        $.notify({
            icon: 'ti-face-smile',
            message: "Bem vindo ao Liber!"

        }, {
            type: 'danger',
            timer: 4000
        });

    });
</script>

</html>

usuarios/templates/dashboard/base_emprestimos.html
{% extends 'dashboard/base_dashboard.html' %} {% load staticfiles %} {% block body %}

<!--  Paper Dashboard core CSS    -->
<link href="https://cdn.jsdelivr.net/foundation/6.2.0/foundation.min.css">
<link href="{% static 'assets/css/estante.css'%}" rel="stylesheet" />


<div class="container">
    <ul class="nav nav-tabs"> {% block meus_livros_emprestados %}
        <li> {% endblock %}
            <a href="{% url 'usuarios:emprestados' user=perfil.id %}">Meus Livros Emprestados</a>
        </li>
        {% block livros_devolver %}
        <li> {% endblock %}
            <a href="{% url 'usuarios:livros_devolver' user=perfil.id %}">Livros a Devolver</a>
        </li>
        {% block historico %}
        <li> {% endblock %}
            <a href="{% url 'usuarios:historico' user=perfil.id %}">Histórico</a>
        </li>
    </ul>
    <div class="tab-content">
    {% block listas %}

    {% endblock %}
    </div>


    <script src="{% static 'assets/js/main.js'%}"></script>

    {% endblock %}

</div>

usuarios/templates/dashboard/estante.html
{% extends 'dashboard/base_dashboard.html' %}
{% load staticfiles %}

{% block acompanhamento %}
<li>
{% endblock %}
{% block estante %}
<li class="active">
{% endblock %}


{% block body %}

<link href="https://cdn.jsdelivr.net/foundation/6.2.0/foundation.min.css">
<link href="{% static 'assets/css/estante.css' %}" rel="stylesheet" />

<div class="content">
                <!-- <div class="container-fluid">
                    <div class="catalog-search">
                        <input class="shuffle-search input_field " type="search" autocomplete="off" value="" maxlength="128" id="input-search" />
                        <label class="input_label" for="input-search">
                            <span class="input_label-content">Search Library</span>
                            <span class="input_label-search"></span>
                        </label>
                    </div> -->

                <!-- Main Section -->
                <div class="page-container">

                    <section id="book_list">

                        <div class="grid-shuffle">
                            <ul id="grid" class="row">
                              {% for estante_livro in estante_livros.all %}
                                <li class="book-item col-lg-6 col-sm-6 card" data-groups='["classic"]' data-date-created='1937' data-title='Of Mice and Men'
                                    data-color='#fcc278'>
                                    <div class="bk-img">
                                        <div class="bk-wrapper">
                                            <div class="bk-book bk-bookdefault">
                                                <div class="bk-front">
                                                    <div class="bk-cover">
                                                      <img src="{{ estante_livro.livro_adicionado.imagem.url }}" onclick="window.location.href= '{% url 'livros:livros_detail_logado' pk=estante_livro.livro_adicionado.id %}' "/>
                                                    </div>
                                                </div>
                                                <div class="bk-back"></div>
                                                <div class="bk-left"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="item-details">
                                        <h3 class="book-item_title">{{ estante_livro.livro_adicionado.titulo }}</h3>
                                        <p class="author">{{ estante_livro.livro_adicionado.autores }} </p>
                                        <div class="col-xs-2">
                                            <div class="icon-big icon-color">

                                                <i class="fa fa-book"></i>
                                            </div>
                                        </div>
                                        <div class="col-xs-5">
                                            {% if estante_livro.status == 'D'  %}
                                            <h4> <font color='green'> {{estante_livro.get_status_display }}</font> </h4>
                                            {% endif %}

                                            {% if estante_livro.status == 'E'  %}
                                            <h4> <font color='red'> {{estante_livro.get_status_display }}</font> </h4>
                                            {% endif %}

                                        </div>
                                        {% if request.user.perfil.id != perfil.id and estante_livro.status == 'D'  %}
                                          <div>
                                              <a class="btn btn-sm btn-success btn-icon" href="{% url 'usuarios:pedir_emprestado_detail' user=estante_livro.estante.perfil_dono.id livro=estante_livro.livro_adicionado.id %}">Pedir emprestado</a>
                                          </div>
                                          <div class="modal fade" id="emprestimoLivro" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                <div class="modal-header">
                                                  <h5 class="modal-title" id="ModalLabel">Pedido de empréstimo</h5>
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                  </button>
                                                </div>
                                                <div class="modal-body">
                                                  <form action="{% url 'usuarios:pedir_emprestado' user=estante_livro.estante.perfil_dono.id livro=estante_livro.livro_adicionado.id %}" method="post" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    {{ form_emprestimo.non_field_errors }}
                                                    <div class='fieldWrapper'>
                                                      {{ form_emprestimo.data_devolucao.errors }}
                                                      <label for="{{form.nota.id_for_label}}">Data de devolução desejada:</label>
                                                      {{ form_emprestimo.data_devolucao }}
                                                    </div>
                                                    <div class='fieldWrapper'>
                                                      {{ form_emprestimo.mensagem_de_quem_pede.errors }}
                                                      <label for="{{form.nota.id_for_label}}">Quer acrescentar alguma mensagem:</label>
                                                      {{ form_emprestimo.mensagem_de_quem_pede }}
                                                    </div>
                                                    <div class="modal-footer">
                                                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                                      <button class="btn btn-primary" type="submit" value="OK">Fazer pedido</button>
                                                    </div>

                                                  </form>
                                                </div>
                                              </div>
                                            </div>
                                          </div>


                                        {% endif %}
                                        <br>
                                        {% if request.user.perfil.id == perfil.id %}
                                          <div>
                                            <a class="btn btn-danger" href="{% url 'usuarios:altera_status_livro' user=perfil.id livro=estante_livro.livro_adicionado.id %}">Alterar status</a>
                                          </div>
                                          <div>
                                            <a class="btn btn-danger" href="{% url 'usuarios:apagar_livro' user=perfil.id livro=estante_livro.livro_adicionado.id %} ">Apagar livro</a>
                                          </div>
                                        {% endif %}
                                    </div>

                                </li>
                              {% endfor %}
                            </ul>
                          </div>

                        </section>

                      </div>


                    </div>
                    <!-- /main -->

        <div class="main-overlay">
            <div class="overlay-full"></div>
        </div>

</div>
<!-- /main-container -->


{% endblock %}

usuarios/templates/dashboard/sugestao.html
{% if sugestao %}
  <ul>
    {% for livross in sugestao %}
    <li><a href= "{% url 'livros:livros_detail' pk=livross.id %}" >{{ livross.titulo }} - {{ livross.autores.first}} </a></li>
        {%for cat in livross.categorias.all%}
            {{cat}},
        {% endfor %}
    {% endfor %}
  </ul>
{% else %}
  <p>Não tem livro registrado</p>
{% endif %}