liber/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from usuarios.views import UserCreate, logout_view
from livros.views import LivroIndex

from liber import settings

urlpatterns = [
    path('', LivroIndex.as_view(), name='livros_index'),
    path('admin/', admin.site.urls),
    path('livros/', include('livros.urls')),
    path('perfil/', include('usuarios.urls')),

    path('login/', auth_views.login, {'template_name':'perfil/login.html'}, name="login"),
    path('logout/', logout_view, name ="logout"),
    path('cadastrar/',UserCreate.as_view(), name="cadastrar"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
# from views import RegistrarUsuarioView

# papra importar imagem
from django.conf import settings
from django.conf.urls.static import static

# Django local
from . import views
from livros.views import apagar_livro_da_estante, altera_status_livro

app_name = 'usuarios'
urlpatterns = [

    path('', login_required(views.UserIndex.as_view()), name='usuarios_index'),
    path('<int:pk>', views.UserDetail.as_view(), name='home'),
    path('<int:user>/estante', login_required(views.PerfilEstanteList.as_view()), name='estante'),
    path('<int:user>/estante/<int:livro>/apagar', apagar_livro_da_estante, name='apagar_livro' ),
    path('<int:user>/estante/<int:livro>/alterar', altera_status_livro, name='altera_status_livro' ),
    path('<int:user>/estante/<int:livro>', views.LivroEmprestimoDetail.as_view(), name='pedir_emprestado_detail'),
    path('<int:user>/estante/<int:livro>/emprestimo', views.fazer_pedido_de_emprestimo, name='pedir_emprestado'),
    path('<int:user>/avaliacaolivro',(views.LivrosAvaliados.as_view()), name='avaliacaolivro'),
    path('<int:user>/sugestao', views.SugestaoLivro.as_view(), name='sugestao' ),
    path('<int:user>/avaliacao',views.Avaliacao.as_view(), name='avaliacao'),
    path('<int:user>/emprestimos', views.livros_emprestados.as_view(), name='emprestados'),
    path('<int:user>/emprestimos/<int:emprestimo>', views.EmprestimoDetail.as_view(), name='emprestimo_detail'),
    path('<int:user>/emprestimos/<int:emprestimo>/aceita', views.aceitar_emprestimo, name='aceita_emprestimo'),
    path('<int:user>/emprestimos/<int:emprestimo>/cancela', views.cancelar_emprestimo, name='cancelar_emprestimo'),
    path('<int:user>/devolver/<int:emprestimo>/devolver', views.devolver_livro, name='devolver_livro'),
    path('<int:user>/emprestimos/<int:emprestimo>/avaliar', views.confirmar_devolucao, name='avaliar_emprestimo'),
    path('<int:user>/devolver', views.livros_devolver.as_view(), name='livros_devolver'),
    path('<int:user>/historico', views.historico.as_view(), name='historico'),
    #path('<int:user>/testeemprestimo', views.teste_historico_emprestimo.as_view(), name='testeemprestimo'),
    #path('<int:user>/testeemprestimo/<int:emprestimo>/aceita', views.aceitar_emprestimo, name='aceita_emprestimo'),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/models.py
from django.db import models

from livros.models import Livro, Categoria

from django.contrib.auth.models import User

SEXO_USUARIO = (
    ('F', 'Feminino'),
    ('M', 'Masculino'),
)

NOTA_LIDO = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5),
    (6, 6),
    (7, 7),
    (8, 8),
    (9, 9),
    (10, 10),
)

STATUS_EMPRESTIMO = (
    ('S', 'Solicitado'),
    ('EA', 'Em andamento'),
    ('OK', 'Concluído'),
    ('ED', 'Em Devolução'),
    ('C', 'Cancelado')
)


class Perfil(models.Model):

    usuario = models.OneToOneField(User, on_delete=models.CASCADE, unique=True)
    telefone = models.CharField(max_length=15, null=True)
    data_de_nascimento = models.DateField(blank=True)
    sexo = models.CharField(max_length=1, choices=SEXO_USUARIO, blank=True , null=True)
    categorias_preferidas = models.ManyToManyField(Categoria)
    imagem_perfil = models.ImageField(upload_to='imagem_perfil/', default='imagem_perfil/user.png')
    livros = models.ManyToManyField(Livro, through='AvaliaLido' )


    def __str__(self):
        return self.usuario.username

    class Meta:
        verbose_name='Perfil'
        verbose_name_plural= "Perfis"


"""
    @property
    def email(self):
        return self.usuario.email
"""
STATUS_LIVRO = (
    ('D', 'Disponível'),
    ('E', 'Emprestado'),
)

class Estante(models.Model):

    nome = models.CharField(max_length=30, blank=False , default="Estante")
    perfil_dono = models.OneToOneField(Perfil,  on_delete=models.CASCADE, null=True)
    livros = models.ManyToManyField(Livro, through='EstanteLivro')

    def __str__(self):
        return '{}-> {}'.format(self.nome, self.perfil_dono)


class EstanteLivro(models.Model):
    estante = models.ForeignKey(Estante, on_delete=models.CASCADE)
    livro_adicionado = models.ForeignKey(Livro, on_delete=models.CASCADE)
    data_adicionado = models.DateField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_LIVRO, blank=False , null=False, default='D')

    def __str__(self):
        return '{}-> {}'.format(self.estante, self.livro_adicionado)

class AvaliaLido (models.Model):

    lido = models.BooleanField(default=False)
    perfil_avaliador= models.ForeignKey(Perfil, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE)
    nota = models.IntegerField(choices=NOTA_LIDO, null=False)
    comentario = models.TextField(null=True, blank=True)

    def __str__(self):
        return '{} {} {}'.format(self.livro, self.perfil_avaliador, self.nota)


class Emprestimo (models.Model):
    perfil_do_dono = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name="solicitado")
    perfil_solicitante = models.ForeignKey(Perfil, on_delete=models.CASCADE, related_name="solicitante")
    livro_emprestado = models.ForeignKey(EstanteLivro, on_delete=models.CASCADE)
    data_emprestimo= models.DateField(auto_now=True)
    data_devolucao= models.DateField(null=True)
    status_emprestimo = models.CharField(max_length=2, choices=STATUS_EMPRESTIMO, blank=False , null=False, default='S')
    mensagem_de_quem_pede = models.CharField(null=True, blank=True, max_length=200)
    mensagem_resposta = models.CharField(null=True, blank=True,max_length=200)

    def __str__(self):
        return'Dono >{}, para {},{}'.format(self.perfil_do_dono.usuario.username, self.perfil_solicitante, self.livro_emprestado)


class AvaliaEmprestimo (models.Model):
    nota = models.IntegerField(choices=NOTA_LIDO)
    Emprestimo_avaliado = models.OneToOneField(Emprestimo, on_delete=models.CASCADE)
    mensagem_de_avaliacao = models.CharField(null=True, blank=True,max_length=200)

    def __str__(self):
        return '{}'.format(self.Emprestimo_avaliado)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import Perfil, AvaliaLido, Emprestimo, AvaliaEmprestimo

SEXO_USUARIO = (
    ('F', 'Feminino'),
    ('M', 'Masculino'),
)

class CadastroForm(UserCreationForm):

    telefone = forms.CharField()
    data_de_nascimento = forms.DateField()
    sexo = forms.ChoiceField(widget=forms.Select, choices=SEXO_USUARIO) #SelectCharWidget(sexo=SEXO_USUARIO))
    #imagem_perfil = forms.ImageField()

    class Meta:
        model = User
        fields = ('username','password1','password2','telefone','data_de_nascimento','sexo')#,'imagem_perfil')

"""
class RegistrarUsuarioForm(forms.Form):

    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    data_de_nascimento = forms.DateField(required=True)
    sexo = forms.CharField(required=True)
    imagem_perfil = forms.ImageField(required=False)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor verifique os dados informados.')
            valid = False

        user_exists = User.objects.filter(username=self.data['email']).exists()

        if user_exists:
            self.adiciona_erro('Usuário ja existente')
            valid = False
        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)
"""

class AvaliaForm(ModelForm):
    class Meta:
        model = AvaliaLido
        fields = ['nota','comentario']

class PedirLivroEmprestadoForm(ModelForm):
    class Meta:
        model = Emprestimo
        fields = ['data_devolucao', 'mensagem_de_quem_pede']

class EmprestimoForm(ModelForm):
    class Meta:
        model = Emprestimo
        fields = ['mensagem_resposta']
        #mensagem_de_quem_pede = forms.CharField(required=False, widget=forms.Textarea(attrs={'class':'form-control','rows':1,'cols':10,'placeholder':'keword values'}))


class AvaliacaoEmprestimoForm(ModelForm):
    class Meta:
        model = AvaliaEmprestimo
        fields = ['nota','mensagem_de_avaliacao']

usuarios/templates/usuarios/detail.html
{% load staticfiles %}

<h2> {{ usuario.nome }}</h2>

<ul>
  <li>Nome: {{ usuario.nome }}</li>
  <li>Sexo: {{ usuario.sexo }}</li>
  <li>Telefone: {{ usuario.telefone }}</li>
  {% if usuario.imagem_perfil %}
  <li><img src="{{ usuario.imagem_perfil.url }}" width="100px" height="100px"</li>
  {% endif %}
</ul>
  {{ form.imagem_perfil }}

<a href="{% url 'usuarios:usuarios_edit' pk=usuario.id %}"> Editar</a>
<form action="{% url 'usuarios:usuarios_delete' pk=usuario.id %}" method='post'>
  {% csrf_token %}
  <input type="submit" onclick="return confirm('Deseja apagar o cadastro?')" value="Apagar conta">
</form>

usuarios/templates/usuarios/edit.html
<h2>Editar cadastro</h2>

<form action="{% url 'usuarios:usuarios_edit' pk=usuario.id %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Salvar">
</form>

usuarios/templates/usuarios/index.html
  {% load staticfiles %}
  <!doctype html>
  <html lang="en">

  <head>
      <meta charset="utf-8" />
      <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png"%}">
      <link rel="icon" type="image/png" sizes="96x96" href="{% static "assets/img/favicon.png"%}">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

      <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
      <meta name="viewport" content="width=device-width" />

      <link href="{% static "assets/css/bootstrap2.min.css"%}" rel="stylesheet" />

      <!-- Animation library for notifications   -->
      <link href="{% static "assets/css/animate.min.css"%}" rel="stylesheet" />

      <!--  Paper Dashboard core CSS    -->
      <link href="{% static "assets/css/paper-dashboard.css"%}" rel="stylesheet" />
      <link href="{% static "assets/css/dashboard.css"%}" rel="stylesheet" />

      <!--  Fonts and icons     -->
      <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
      <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
      <link href="{% static "assets/css/themify-icons.css"%}" rel="stylesheet">

  </head>

  <body>
      <center>
      <div>
          <div data-background-color="white" data-active-color="danger">
              <div class="sidebar-wrapper">
                      <a href="{% url 'livros_index' %}" class="simple-text">
                          <img src="{% static "assets/img/logo-letras.png"%}" class="logotipo" />
                      </a>

                </div >
                </div>

                </div>
                 {% if usuario_list %}
                      {% for perfil in usuario_list %}
                      <li class="book-item col-lg-2" data-color='#fcc278'>
                          <div class="avatar">
                              <img src="{{ perfil.imagem_perfil.url }}" style="margin:5px; width:40px; height:40px"  alt="Circle Image" class="img-circle img-no-padding img-responsive"  >
                          </div>
                        <a href="{% url 'usuarios:estante' perfil.id %}"><h5>{{ perfil.usuario.username }}</h5></a>
                        {% endfor %}

                      {% else %}
                        <p>Não tem usuário cadastro</p>
                        {% endif %}    </div>


                    </div>
                </div>
            </div>                        </li>


      </center>
      </div>
  </div>

usuarios/templates/usuarios/login.html
<form class="form-signin" role="form"
  action="{% url 'usuarios:usuarios_new' %}" method="post">
  {% csrf_token %}
  <h2 class="form-signin-heading">Login</h2>

  <input id="id_username" name="username" type="text" class="form-control"
  placeholder="Nome" required autofocus>

  <input id="id_password" name="password" type="password" class="form-control"
  placeholder="Senha" required>

  <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>

  <input type="hidden" name="next" value="{{ next }}"/>


  <hr/>
  {% if form.errors %}
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      Por favor, verifique o Email e/ou Senha informados
    </div>
  {% endif %}

   <a href="{% url 'registrar' %}">registre-se</a>

usuarios/templates/usuarios/new.html
<h2>Novo Cadastro</h2>

<form action="{% url 'usuarios:usuarios_new' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}

  <input type="submit" value="Cadastrar">
</form>

usuarios/templates/usuarios/registrar.html
<form class="form-signin" action="{% url 'registrar' %}" method="post">
  {% csrf_token %}
  <h2 class="form-signin">Crie seu usuário</h2>

  <input id="id_email" name="email" type="text" class="form-control"
  placeholder="Email *" required>

  <input id="id_nome" name="nome" type="text" class="form-control"
  placeholder="Nome *" required>

  <input id="id_senha" name="senha" type="password" class="form-control"
  placeholder="Senha *" required>

  <input id="id_telefone" name="telefone" type="text" class="form-control"
  placeholder="Telefone">

  <input id="id_nome_empresa" name="nome_empresa" type="text" class="form-control"
  placeholder="Empresa">

  <hr/>
  {% if form.errors %}
    <div class="alert alert-danger">
      <button type="button" class="close">&times;</button>
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  <button class="btn btn-lg btn-primary btn-block" type="submit">Registrar</button>


</form>