liber/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from usuarios.views import UserCreate, logout_view
from livros.views import LivroIndex

from liber import settings

urlpatterns = [
    path('', LivroIndex.as_view(), name='livros_index'),
    path('admin/', admin.site.urls),
    path('livros/', include('livros.urls')),
    path('perfil/', include('usuarios.urls')),

    path('login/', auth_views.login, {'template_name':'perfil/login.html'}, name="login"),
    path('logout/', logout_view, name ="logout"),
    path('cadastrar/',UserCreate.as_view(), name="cadastrar"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

livros/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.conf.urls.static import static

# Django local
from . import views
from usuarios.views import marcar_livro_lido
#, AvaliaLidoCreate


app_name = 'livros'
urlpatterns = [
    #path('', views.LivroIndex.as_view(), name='livros_index'),
    path('', views.ListLivros.as_view(), name='lista_livros'),
    path('<int:pk>/', views.LivroDetail.as_view(), name='livros_detail'),
    path('<int:pk>/detail', login_required(views.LivroDetailLogado.as_view()), name='livros_detail_logado'),
    path('new', views.LivroCreate.as_view(), name='livros_new'),
    path('autor/new', views.AutorCreate.as_view(), name='autor_new'),
    path('<int:pk>/edit', views.LivroUpdate.as_view(), name='livros_edit'),
    path('<int:pk>/delete', views.LivroDelete.as_view(), name='livros_delete'),
    path('<int:pk>/adiciona', views.adiciona_livro_na_estante, name='adiciona'),
    path('<int:pk>/lido', marcar_livro_lido, name='livrolido'),
    path('<int:pk>/medialivros', views.media_cada_livro, name='medialivros'),
    path('<int:pk>/avalia', views.AvaliaLidoCreate.as_view(), name='avalia_livro'),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

usuarios/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
# from views import RegistrarUsuarioView

# papra importar imagem
from django.conf import settings
from django.conf.urls.static import static

# Django local
from . import views
from livros.views import apagar_livro_da_estante, altera_status_livro

app_name = 'usuarios'
urlpatterns = [

    path('', login_required(views.UserIndex.as_view()), name='usuarios_index'),
    path('<int:pk>', views.UserDetail.as_view(), name='home'),
    path('<int:user>/estante', login_required(views.PerfilEstanteList.as_view()), name='estante'),
    path('<int:user>/estante/<int:livro>/apagar', apagar_livro_da_estante, name='apagar_livro' ),
    path('<int:user>/estante/<int:livro>/alterar', altera_status_livro, name='altera_status_livro' ),
    path('<int:user>/estante/<int:livro>', views.LivroEmprestimoDetail.as_view(), name='pedir_emprestado_detail'),
    path('<int:user>/estante/<int:livro>/emprestimo', views.fazer_pedido_de_emprestimo, name='pedir_emprestado'),
    path('<int:user>/avaliacaolivro',(views.LivrosAvaliados.as_view()), name='avaliacaolivro'),
    path('<int:user>/sugestao', views.SugestaoLivro.as_view(), name='sugestao' ),
    path('<int:user>/avaliacao',views.Avaliacao.as_view(), name='avaliacao'),
    path('<int:user>/emprestimos', views.livros_emprestados.as_view(), name='emprestados'),
    path('<int:user>/emprestimos/<int:emprestimo>', views.EmprestimoDetail.as_view(), name='emprestimo_detail'),
    path('<int:user>/emprestimos/<int:emprestimo>/aceita', views.aceitar_emprestimo, name='aceita_emprestimo'),
    path('<int:user>/emprestimos/<int:emprestimo>/cancela', views.cancelar_emprestimo, name='cancelar_emprestimo'),
    path('<int:user>/devolver/<int:emprestimo>/devolver', views.devolver_livro, name='devolver_livro'),
    path('<int:user>/emprestimos/<int:emprestimo>/avaliar', views.confirmar_devolucao, name='avaliar_emprestimo'),
    path('<int:user>/devolver', views.livros_devolver.as_view(), name='livros_devolver'),
    path('<int:user>/historico', views.historico.as_view(), name='historico'),
    #path('<int:user>/testeemprestimo', views.teste_historico_emprestimo.as_view(), name='testeemprestimo'),
    #path('<int:user>/testeemprestimo/<int:emprestimo>/aceita', views.aceitar_emprestimo, name='aceita_emprestimo'),



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

livros/models.py
from django.db import models


class Autor(models.Model):

    nome = models.CharField(max_length=100, null=False)
    sobrenome = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name='Autor'
        verbose_name_plural= "Autores"


class Categoria(models.Model):

    descricao = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.descricao

class Livro(models.Model):
    isbn10 = models.CharField('ISBN', max_length=10, help_text='10 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', default='1234567890')
    isbn13 = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', default='123456784')
    titulo = models.CharField(max_length=200, null=False)
    editora = models.CharField(max_length=200, null=False)
    descricao = models.TextField()
    paginas = models.IntegerField(null=False, default=50)
    idioma= models.CharField(max_length=200, null=False, default="pt-br")
    imagem = models.ImageField(upload_to='imagem_livro/', default='imagem_livro/livro.png')
    edicao = models.IntegerField(null=False, default=1)
    ano = models.IntegerField(null=False, default=2014)
    autores = models.ManyToManyField(Autor)
    categorias = models.ManyToManyField(Categoria)

    def nota_media(self):
        avaliados = self.avalialido_set.all()
        media = 0
        if avaliados:
            notas = 0


            for avaliado in avaliados:
                notas += avaliado.nota

            media = notas/len(avaliados)

        return media

    def __str__(self):
        return '{}-> {}'.format(self.titulo, self.categorias.all())

livros/forms.py
from django.forms import ModelForm
from django import forms

from .models import Autor, Categoria, Livro

class LivroForm(ModelForm):
    #autores = forms.ModelMultipleChoiceField(queryset=Autor.objects.all(), required=False, widget=forms.CheckboxSelectMultiple())
    #categorias = forms.ModelMultipleChoiceField(queryset=Categoria.objects.all(), required=False, widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = Livro
        fields = ['titulo', 'editora', 'isbn10', 'isbn13', 'descricao', 'paginas', 'autores', 'edicao', 'ano', 'categorias' ] #, 'imagem']


class AutorForm(ModelForm):
    class Meta:
        model = Autor
        fields = ['nome', 'sobrenome']

livros/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404

from .models import Autor, Categoria, Livro
from usuarios.models import Perfil, Estante, EstanteLivro, AvaliaLido, Emprestimo
from usuarios.forms import AvaliaForm, EmprestimoForm , PedirLivroEmprestadoForm
from .forms import LivroForm, AutorForm

import operator

class LivroIndex(generic.ListView):
    template_name = 'livros/index.html'
    context_object_name = 'livro_list'

    def get_queryset(self):
        livros = Livro.objects.all()
        sorted_livro = sorted(livros, key=lambda livro: livro.nota_media())
        sorted_livro.reverse()
        return sorted_livro[:4]


class ListLivros(generic.ListView):
    template_name = 'livros/listall.html'
    context_object_name = 'livro_list'

    def get_queryset(self):
        return Livro.objects.order_by('titulo')

class LivroDetail(generic.DetailView):


    model = Livro
    template_name = 'livros/detail.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data()
        #perfil = self.request.user.perfil
        context['medialivros'] = media_cada_livro(self.request, pk=self.kwargs['pk'])
        if self.request.user.is_authenticated:
            perfil = get_object_or_404(Perfil, pk=self.request.user.perfil.id)
            livro = Livro.objects.get(pk=self.kwargs['pk'])
            context['estante_livros'] = perfil.estante.estantelivro_set.filter(livro_adicionado=livro)
            context['livros_lidos_total'] = perfil.avalialido_set.all()
            context['livros_lidos'] = perfil.avalialido_set.filter(livro=livro)


        return context


class LivroDetailLogado(generic.DetailView):
    model = Livro
    template_name = 'livros/detail_logado.html'

    def get_context_data(self, **kwargs):

        context = super().get_context_data()
        #perfil = self.request.user.perfil

        if self.request.user.is_authenticated:
            perfil = get_object_or_404(Perfil, pk=self.request.user.perfil.id)
            livro = Livro.objects.get(pk=self.kwargs['pk'])
            context['estante_livros'] = perfil.estante.estantelivro_set.filter(livro_adicionado=livro)
            context['livros_lidos_total'] = perfil.avalialido_set.all()
            context['livros_lidos'] = perfil.avalialido_set.filter(livro=livro)
            context['medialivros'] = media_cada_livro(self.request, pk=self.kwargs['pk'])
            context['estantes_com_livro'] = EstanteLivro.objects.filter(livro_adicionado=livro)
            context['form'] = AvaliaForm()
            context['form_emprestimo'] = PedirLivroEmprestadoForm()

        return context



class LivroCreate(generic.CreateView):
    model = Livro
    template_name = 'livros/new.html'
    success_url = reverse_lazy('livros:livros_index')
    #__import__('ipdb').set_trace()
    form_class = LivroForm

class AutorCreate(generic.CreateView):
    model = Autor
    template_name = 'livros/newautor.html'
    success_url = reverse_lazy('livros:livros_new')
    form_class = AutorForm


class LivroUpdate(generic.UpdateView):
    model = Livro
    template_name = 'livros/edit.html'
    form_class = LivroForm

    def get_success_url(self):
        return reverse_lazy('livros:livros_detail', kwargs={'pk':self.kwargs['pk']})

class LivroDelete(generic.DeleteView):
    model = Livro
    success_url = reverse_lazy('livros:livros_index')

@login_required
def adiciona_livro_na_estante(request, pk):

    estante = Estante.objects.get(perfil_dono=request.user.perfil)
    livros_da_estante = estante.livros.all()
    livro = Livro.objects.get(pk=pk)

    if (livro not in livros_da_estante):
        estante.estantelivro_set.create(estante=estante,livro_adicionado=livro)

    return redirect('usuarios:estante', user=request.user.perfil.id)

@login_required
def apagar_livro_da_estante(request, livro, user):

    estante = Estante.objects.get(perfil_dono = request.user.perfil)
    livros_da_estante = estante.livros.all()
    livro = Livro.objects.get(pk=livro)

    #import ipdb; ipdb.set_trace()

    if (livro in livros_da_estante):
        livro_para_apagar = estante.estantelivro_set.get(livro_adicionado=livro)
        livro_para_apagar.delete()

    return redirect('usuarios:estante', user=request.user.perfil.id)


def altera_status_livro(request, livro, user):

    #perfil = get_object_or_404(Perfil, pk=kwargs['user'])
    #estantes = perfil.estante.estantelivro_set.all().order_by('status')
    estante = Estante.objects.get(perfil_dono = request.user.perfil)
    livros_da_estante = estante.livros.all()
    livro = Livro.objects.get(pk=livro)
    #__import__('ipdb').set_trace()
    if (livro in livros_da_estante):
        livro_para_alterar = estante.estantelivro_set.get(livro_adicionado=livro)
        if (livro_para_alterar.status == 'E'):
            livro_para_alterar.status = 'D'
            livro_para_alterar.save()
        elif (livro_para_alterar.status == 'D'):
            livro_para_alterar.status = 'E'
            livro_para_alterar.save()

    return redirect('usuarios:estante', user=request.user.perfil.id)




def media_cada_livro(request, pk):

    livroComNotas =  Livro.objects.get(pk=pk)
    notas=livroComNotas.avalialido_set.all()
    somaNotas=0
    medialivros=0
    for nota in notas:
        somaNotas += nota.nota
        medialivros=somaNotas/notas.count()

    return medialivros


class AvaliaLidoCreate(generic.CreateView):
    model = AvaliaLido
    template_name = 'livros/detail_logado.html'
    success_url = reverse_lazy('livros_index')
    form_class = AvaliaForm

    def form_valid(self, form):
        livro = Livro.objects.get(pk=self.kwargs['pk'])
        form.instance.perfil_avaliador = self.request.user.perfil
        form.instance.livro = livro
        form.instance.lido = True
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['livro'] = get_object_or_404(Livro, pk=self.kwargs['pk'])

        return context


"""
apagar isso se funcionar
def retorna_estantes_com_o_livro(request):
    estantes = Estante.objects.all()
    livro = Livro.objects.get(pk=livro)
    estantes_com_livro = EstanteLivro.objects.filter(livro_adicionado=livro)
"""

livros/templates/livros/base_index.html
{% load staticfiles %}
<!DOCTYPE html>

<head>
  <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Liber</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}"/>
	<link rel="stylesheet" href="{% static "assets/css/paper-kit.css?v=2.1.0" %}" />
	<link href='http://fonts.googleapis.com/css?family=Montserrat:400,300,700' rel='stylesheet' type='text/css'>
	<link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" href=" {% static "assets/css/nucleo-icons.css" %}">
	<link rel="stylesheet" href=" {% static "assets/css/main.css" %}" >
</head>

<body>
	<nav class="navbar navbar-expand-lg fixed-top navbar-transparent" color-on-scroll="300">
		<div class="container">
			<div class="navbar-translate">
				<a class="container navbar-brand" href="{% url 'livros_index' %}">
					<img id="logotipo" src="{% static "assets/img/logo.png" %} " alt="Logotipo" height="100">
				</a>
				<button class="navbar-toggler navbar-toggler-right navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler"
				    aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-bar"></span>
					<span class="navbar-toggler-bar"></span>
					<span class="navbar-toggler-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="navbarToggler">
				<ul class="navbar-nav ml-auto">
					<li class="search">
						<div class="input-group">
							<input type="search" width="250" placeholder="Pesquisar por título, autor, isbn, assuntos">
							<span class="input-group-btn">
								<button type="button">
									<i class="fa fa-search"></i>
								</button>
							</span>
						</div>
					</li>
					<li class="nav-item" id="search">
						<div class="input-group">
							<input type="search" placeholder="Pesquisar livros">
							<span class="input-group-btn">
								<button type="button">
									<i class="fa fa-search"></i>
								</button>
							</span>
						</div>
					</li>
                    <li>
                        <div class="">
                            <a class="buy-button" href="{% url 'usuarios:usuarios_index' %}">
                                <h5> <b> <font color=purple>  <i class="fa fa-user-circle-o">Usuarios</i> </font> </b> </h5>
                                <br>
                            </a>
                        </div>
                    </li>
                    <li>
                        <div class="">
                            <a class="buy-button" href="{% url 'livros:lista_livros' %}">
                                <h5> <b> <font color=purple> <i class="fa fa-book">Lista de livros</i> </font> </b> </h5>
                                <br>
                            </a>
                        </div>
                    </li>


            {% if user.is_authenticated %}
                    <li class="nav-item">
                        <br>
                        <a href="{% url 'usuarios:home' pk=request.user.perfil.id %}" class="nav-link">
                        <h4>  <font color=purple>  <b> <i class="nc-icon nc-circle-10"></i>Meu Perfil</a></b> </h4>
                    </li>

            {%else %}
                    <li class="nav-item">
                        <a href="{% url 'login' %}" class="nav-link">
                            <i class="nc-icon nc-circle-10"></i>Entrar</a>
                    </li>

            {% endif %}


				</ul>
			</div>
		</div>
	</nav>

  {% block body %}

  {% endblock %}

  <script type="text/javascript" src="{% static "assets/js/jquery-3.2.1.js" %} " ></script>
	<script type="text/javascript" src="{% static "assets/js/jquery-ui-1.12.1.custom.min.js" %}" ></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	    crossorigin="anonymous"></script>
	<script type="text/javascript" src="{% static "assets/js/bootstrap.min.js" %}"></script>
	<script src="{% static "assets/js/paper-kit.js?v=2.1.0" %}"></script>


</body>

livros/templates/livros/edit.html
<h2>Editar livro</h2>

<form action="{% url 'livros:livros_edit' pk=livro.id %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="OK">
</form>

livros/templates/livros/index.html
{% extends "livros/base_index.html" %}
{% load static %}

{% block body %}
<link rel="stylesheet" href=" {% static "assets/css/main.css" %}" >

<div class="mais-avaliados" id="banner">
  <div class="container">
    <h1>Mais bem avaliados</h1>
    {% if livro_list %}
    <ul class='list-inline'>
      {% for livro in livro_list %}
      <li class='book'>
        {% if user.is_authenticated %}
        <img src="{{ livro.imagem.url }}" onclick="window.location.href= '{% url 'livros:livros_detail_logado' pk=livro.id %}' "/>
        {% else %}
        <img src="{{ livro.imagem.url }}" onclick="window.location.href= '{% url 'livros:livros_detail' pk=livro.id %}' "/>
        {% endif %}
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>Não tem livro registrado</p>
    {% endif %}
  </div>
</div>

{% endblock %}

livros/templates/livros/listall.html
      {% load staticfiles %}
      <!doctype html>
      <html lang="en">

      <head>
          <meta charset="utf-8" />
          <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png"%}">
          <link rel="icon" type="image/png" sizes="96x96" href="{% static "assets/img/favicon.png"%}">
          <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

          <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
          <meta name="viewport" content="width=device-width" />

          <link href="{% static "assets/css/bootstrap2.min.css"%}" rel="stylesheet" />

          <!-- Animation library for notifications   -->
          <link href="{% static "assets/css/animate.min.css"%}" rel="stylesheet" />

          <!--  Paper Dashboard core CSS    -->
          <link href="{% static "assets/css/paper-dashboard.css"%}" rel="stylesheet" />
          <link href="{% static "assets/css/dashboard.css"%}" rel="stylesheet" />

          <!--  Fonts and icons     -->
          <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
          <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
          <link href="{% static "assets/css/themify-icons.css"%}" rel="stylesheet">

      </head>

      <body>
          <div>
              <div data-background-color="white" data-active-color="danger">
                  <div class="sidebar-wrapper">
                          <a href="{% url 'livros_index' %}" class="simple-text">
                              <img src="{% static "assets/img/logo-letras.png"%}" class="logotipo" />
                          </a>

                    </div >
                    </div>
                    </div>
                    <center>
                        <font color='#660066'> <b><h1>Todos os livros</h1> </b>
                        </font> <h5> <a class="buy-button" href="{% url 'livros:livros_new' %}">
                            Adicionar livro<i class="fa fa-plus"></i>
                            <br>
                        </a></h5>
                    {% if livro_list %}      {% for livro in livro_list %}
                          <li class="book-item col-lg-4" data-color='#fcc278'>
                              <div class="book-item col-lg-2">
                                  <img src="{{ livro.imagem.url }}" style="margin:5px; width:90px; height:120px"  onclick="window.location.href= '{% url 'livros:livros_detail_logado' pk=livro.id %}' "/>
                              </div>
                              <a href= "{% url 'livros:livros_detail_logado' pk=livro.id %}" >{{ livro.titulo }}</a> <br>
                              {%for cat in livro.categorias.all%}
                                  {{cat}},
                              {% endfor %}
                              <br><br><br><br><br><br><br><br>
                               {% endfor %}

                          {% else %}
                            <p>Não tem usuário cadastro</p>
                            {% endif %}    </div>

                        </div>
                    </div>
                </div>                        </li>

                <h3> <a class="buy-button" href="{% url 'livros:livros_new' %}">
                    Adicionar livro<i class="fa fa-plus"></i>
                    <br>
                </a></h3>
          </center>
          </div>
      </div>

livros/templates/livros/new.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png"%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static "assets/img/favicon.png"%}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <link href="{% static "assets/css/bootstrap2.min.css"%}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static "assets/css/animate.min.css"%}" rel="stylesheet" />

    <!--  Paper Dashboard core CSS    -->
    <link href="{% static "assets/css/paper-dashboard.css"%}" rel="stylesheet" />
    <link href="{% static "assets/css/dashboard.css"%}" rel="stylesheet" />

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static "assets/css/themify-icons.css"%}" rel="stylesheet">

</head>

<body>
    <div>
        <div data-background-color="white" data-active-color="danger">
            <div class="sidebar-wrapper">
                    <a href="{% url 'livros_index' %}" class="simple-text">
                        <img src="{% static "assets/img/logo-letras.png"%}" class="logotipo" />
                    </a>
              </div >
              </div>
              </div>
              <center>
                  <font color='#660066'> <b><h1>Adicionar livro</h1> </b>
                  </font>
                  <a type="button" href="{% url 'livros:autor_new' %}">Adicionar autor</a>
                  <br><br>
                  <form action="{% url 'livros:livros_new' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_fields_errors }}
                    <div class='fieldWrapper'>
                      {{ form.titulo.errors }}
                      <label for={{form.titulo.id_for_label}}>Título:</label>
                      {{ form.titulo }}
                    </div>
                    <div class='fieldWrapper'>
                      {{ form.editora.errors }}
                      <label for={{form.editora.id_for_label}}>Editora:</label>
                      {{ form.editora }}
                    </div>
                    <div class='fieldWrapper'>
                      {{ form.isbn10.errors }}
                      <label for={{form.isbn10.id_for_label}}>ISBN10:</label>
                      {{ form.isbn10 }}
                    </div>
                    <div class='fieldWrapper'>
                      {{ form.isbn13.errors }}
                      <label for={{form.isbn13.id_for_label}}>ISBN13:</label>
                      {{ form.isbn13 }}
                    </div>
                    <div class='fieldWrapper'>
                      {{ form.paginas.errors }}
                      <label for={{form.paginas.id_for_label}}>Páginas:</label>
                      {{ form.paginas }}
                    </div>
                    <div class='fieldWrapper'>
                      {{ form.edicao.errors }}
                      <label for={{form.edicao.id_for_label}}>Edição:</label>
                      {{ form.edicao }}
                    </div>
                    <div class='fieldWrapper'>
                      {{ form.ano.errors }}
                      <label for={{form.ano.id_for_label}}>Ano:</label>
                      {{ form.ano }}
                    </div>
                    <select multiple="multiple">
                      {{ form.autores.errors }}
                      <label for={{form.autores.id_for_label}}>Autores:</label>
                      {{ form.autores }}
                    </select>
                    <div class='fieldWrapper'>
                      {{ form.categorias.errors }}
                      <label for={{form.categorias.id_for_label}}>Categorias:</label>
                      {{ form.categorias }}
                    </div>
                  <!--  <div class='fieldWrapper'>
                      {{ form.imagem.errors }}
                      <label for={{form.imagem.id_for_label}}>Imagem:</label>
                      {{ form.imagem }}
                    </div> -->

                    <input type="submit" value="OK">
                  </form>

    </center>
    </div>
</div>

livros/templates/livros/newautor.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "assets/img/apple-icon.png"%}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static "assets/img/favicon.png"%}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <link href="{% static "assets/css/bootstrap2.min.css"%}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static "assets/css/animate.min.css"%}" rel="stylesheet" />

    <!--  Paper Dashboard core CSS    -->
    <link href="{% static "assets/css/paper-dashboard.css"%}" rel="stylesheet" />
    <link href="{% static "assets/css/dashboard.css"%}" rel="stylesheet" />

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static "assets/css/themify-icons.css"%}" rel="stylesheet">

</head>

<body>
    <div>
        <div data-background-color="white" data-active-color="danger">
            <div class="sidebar-wrapper">
                    <a href="{% url 'livros_index' %}" class="simple-text">
                        <img src="{% static "assets/img/logo-letras.png"%}" class="logotipo" />
                    </a>
              </div >
              </div>
              </div>
              <center>
                  <font color='#660066'> <b><h1>Adicionar Autor</h1> </b>
                  </font>
                  <form action="{% url 'livros:autor_new' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="OK">
                  </form>

    </center>
    </div>
</div>